import type { Movie } from "@reelrank/shared";

export const MOCK_MOVIES: Movie[] = [
  { id: 550, title: "Fight Club", overview: "An insomniac office worker and a devil-may-care soap maker form an underground fight club.", posterPath: "/pB8BM7pdSp6B6Ih7QI4S2t0POoR.jpg", backdropPath: "/hZkgoQYus5dXo3H8T7Uef6DNknx.jpg", releaseDate: "1999-10-15", voteAverage: 8.4, voteCount: 28000, popularity: 75, genreIds: [18, 53] },
  { id: 680, title: "Pulp Fiction", overview: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales.", posterPath: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg", backdropPath: "/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg", releaseDate: "1994-09-10", voteAverage: 8.5, voteCount: 27000, popularity: 80, genreIds: [53, 80] },
  { id: 278, title: "The Shawshank Redemption", overview: "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at Shawshank prison.", posterPath: "/9cjIGRiQPwpDRB7M7acRtWMOuit.jpg", backdropPath: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg", releaseDate: "1994-09-23", voteAverage: 8.7, voteCount: 26000, popularity: 95, genreIds: [18, 80] },
  { id: 155, title: "The Dark Knight", overview: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon, Batman sets out to dismantle the remaining criminal organizations.", posterPath: "/qJ2tW6WMUDux911ma1cYz3TDy63.jpg", backdropPath: "/nMKdUUepR0i5zn0y1T4CsSB5ez4.jpg", releaseDate: "2008-07-16", voteAverage: 8.5, voteCount: 32000, popularity: 90, genreIds: [18, 28, 80, 53] },
  { id: 238, title: "The Godfather", overview: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family.", posterPath: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg", backdropPath: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg", releaseDate: "1972-03-14", voteAverage: 8.7, voteCount: 20000, popularity: 85, genreIds: [18, 80] },
  { id: 13, title: "Forrest Gump", overview: "A man with a low IQ has accomplished great things in his life and been present during significant historic events.", posterPath: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg", backdropPath: "/7c9UVPPiTPltouxRVY6N9uugaVA.jpg", releaseDate: "1994-06-23", voteAverage: 8.5, voteCount: 26500, popularity: 78, genreIds: [35, 18, 10749] },
  { id: 120, title: "The Lord of the Rings: The Fellowship of the Ring", overview: "Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator.", posterPath: "/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg", backdropPath: "/pIUvQ9Ed35wlWhY2oU6OmwEgzx.jpg", releaseDate: "2001-12-18", voteAverage: 8.4, voteCount: 24000, popularity: 88, genreIds: [12, 14, 28] },
  { id: 603, title: "The Matrix", overview: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.", posterPath: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg", backdropPath: "/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg", releaseDate: "1999-03-30", voteAverage: 8.2, voteCount: 25000, popularity: 82, genreIds: [28, 878] },
  { id: 157336, title: "Interstellar", overview: "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel.", posterPath: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg", backdropPath: "/xJHokMbljXjADYdit5fK1EVr7Kt.jpg", releaseDate: "2014-11-05", voteAverage: 8.4, voteCount: 35000, popularity: 92, genreIds: [12, 18, 878] },
  { id: 496243, title: "Parasite", overview: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks, ingrating themselves into their lives.", posterPath: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg", backdropPath: "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg", releaseDate: "2019-05-30", voteAverage: 8.5, voteCount: 18000, popularity: 86, genreIds: [35, 18, 53] },
  { id: 569094, title: "Spider-Man: Across the Spider-Verse", overview: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.", posterPath: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg", backdropPath: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg", releaseDate: "2023-05-31", voteAverage: 8.4, voteCount: 7000, popularity: 94, genreIds: [16, 28, 12, 878] },
  { id: 438631, title: "Dune", overview: "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe.", posterPath: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg", backdropPath: "/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg", releaseDate: "2021-09-15", voteAverage: 7.8, voteCount: 12000, popularity: 89, genreIds: [878, 12] },
  { id: 385687, title: "Fast X", overview: "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path.", posterPath: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg", backdropPath: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg", releaseDate: "2023-05-17", voteAverage: 7.0, voteCount: 5000, popularity: 96, genreIds: [28, 80, 53] },
  { id: 872585, title: "Oppenheimer", overview: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.", posterPath: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg", backdropPath: "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg", releaseDate: "2023-07-19", voteAverage: 8.1, voteCount: 9000, popularity: 97, genreIds: [18, 36] },
  { id: 693134, title: "Dune: Part Two", overview: "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.", posterPath: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg", backdropPath: "/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg", releaseDate: "2024-02-27", voteAverage: 8.2, voteCount: 6500, popularity: 98, genreIds: [878, 12, 28] },
  { id: 11, title: "Star Wars", overview: "Princess Leia is captured and held hostage by the evil Imperial forces. Luke Skywalker and Han Solo must free her and destroy the Death Star.", posterPath: "/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg", backdropPath: "/zqkmTXzjkAgXmEWLRsY4UpTWCeo.jpg", releaseDate: "1977-05-25", voteAverage: 8.2, voteCount: 20000, popularity: 83, genreIds: [12, 28, 878] },
  { id: 346698, title: "Barbie", overview: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land.", posterPath: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg", backdropPath: "/nHf61UzkfFno5X1ofIhugCPus2R.jpg", releaseDate: "2023-07-19", voteAverage: 7.0, voteCount: 8500, popularity: 93, genreIds: [35, 12, 14] },
  { id: 19995, title: "Avatar", overview: "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission.", posterPath: "/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg", backdropPath: "/Yc9q6QuWrMp9nuDm3dcNPKyDoJJ.jpg", releaseDate: "2009-12-15", voteAverage: 7.6, voteCount: 30000, popularity: 87, genreIds: [28, 12, 14, 878] },
  { id: 539681, title: "DC League of Super-Pets", overview: "When Superman and the rest of the Justice League are kidnapped, Krypto the Super-Dog must convince a rag-tag shelter pack to master their own newfound powers.", posterPath: "/r7XifzvtezNt31ypvsmb6lkLuk6.jpg", backdropPath: "/pJ1GGfFdlOowni3t3MFNH2jTQ4y.jpg", releaseDate: "2022-07-27", voteAverage: 7.3, voteCount: 2000, popularity: 72, genreIds: [16, 28, 12, 35, 10751] },
  { id: 466420, title: "Killers of the Flower Moon", overview: "When oil is discovered beneath Osage Nation land, members of the tribe begin to be murdered one by one.", posterPath: "/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg", backdropPath: "/1X7vow16X7CnCoexXh4H4F2yDJv.jpg", releaseDate: "2023-10-18", voteAverage: 7.5, voteCount: 4000, popularity: 84, genreIds: [80, 18, 36] },
];

export const MOCK_GENRES = [
  { id: 28, name: "Action" },
  { id: 12, name: "Adventure" },
  { id: 16, name: "Animation" },
  { id: 35, name: "Comedy" },
  { id: 80, name: "Crime" },
  { id: 99, name: "Documentary" },
  { id: 18, name: "Drama" },
  { id: 10751, name: "Family" },
  { id: 14, name: "Fantasy" },
  { id: 36, name: "History" },
  { id: 27, name: "Horror" },
  { id: 10402, name: "Music" },
  { id: 9648, name: "Mystery" },
  { id: 10749, name: "Romance" },
  { id: 878, name: "Science Fiction" },
  { id: 53, name: "Thriller" },
  { id: 10752, name: "War" },
  { id: 37, name: "Western" },
];
